CREATE OR REPLACE FUNCTION GIVE_FARE (FROM_STAION IN NUMBER,TO_STATION IN NUMBER,CLASS_NAME IN VARCHAR2) RETURN NUMBER IS
FARE NUMBER;
BEGIN
    SELECT AMOUNT INTO FARE FROM FARE WHERE FROM_ST = FROM_STAION AND TO_ST = TO_STATION AND CLASS = CLASS_NAME;
    RETURN FARE;
END;
/

SELECT GIVE_FARE(1,51,'SNIGDHA') FROM DUAL;