-- CREATE TABLE users(
-- nid varchar2(15),
-- username VARCHAR2(40),
-- email VARCHAR2(50),
-- password VARCHAR2(20)
-- );

-- CREATE TABLE Passenger (
--     NID VARCHAR2(15) CONSTRAINT PASSENGER_PK PRIMARY KEY,
--     First_Name VARCHAR2(50) NOT NULL,
--     Last_Name VARCHAR2(50) NOT NULL,
--     Date_Of_Birth DATE NOT NULL,
--     Contact_No VARCHAR2(11) NOT NULL,
--     Email VARCHAR2(100) NOT NULL
-- );

-- DROP TABLE PASSENGER

CREATE TABLE PASSENGERS(
    NID VARCHAR2(15) CONSTRAINT PASSENGERS_PK PRIMARY KEY,
    FIRST_NAME VARCHAR2(50) NOT NULL,
    LAST_NAME VARCHAR2(50) NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    CONTACT_NO VARCHAR2(11) NOT NULL,
    EMAIL VARCHAR2(100)
);

CREATE TABLE TRAINS(
TRAIN_ID NUMBER CONSTRAINT TRAINS_PK PRIMARY KEY,
TRAIN_NAME VARCHAR2(30) NOT NULL
);

CREATE TABLE TRAIN_HOLIDAY (
    TRAIN_ID NUMBER,
    HOLIDAY VARCHAR2(15),
    CONSTRAINT TRAIN_HOLIDAY_PK PRIMARY KEY (TRAIN_ID, HOLIDAY),
    CONSTRAINT TRAIN_HOLIDAY_FK FOREIGN KEY (TRAIN_ID) REFERENCES TRAINS (TRAIN_ID)
);


CREATE TABLE STATIONS(
STATION_ID NUMBER CONSTRAINT STATIONS_PK PRIMARY KEY,
STATION_NAME VARCHAR2(30) NOT NULL
);

CREATE TABLE TRAIN_STOPS (
    TRAIN_ID NUMBER,
    STATION_ID NUMBER,
    ARR_TIME VARCHAR2(10) ,
    DEPT_TIME VARCHAR2(10) ,
    STOP_TYPE VARCHAR2(10) NOT NULL,
    CONSTRAINT TRAIN_STOPS_PK PRIMARY KEY (TRAIN_ID, STATION_ID),
    CONSTRAINT TRAIN_STOPS_FK1 FOREIGN KEY (TRAIN_ID) REFERENCES TRAINS (TRAIN_ID),
    CONSTRAINT TRAIN_STOPS_FK2 FOREIGN KEY (STATION_ID) REFERENCES STATIONS (STATION_ID)
);

CREATE TABLE COMPARTMENTS(
COMPARTMENT_ID NUMBER CONSTRAINT COMPARTMENTS_PK PRIMARY KEY,
TRAIN_ID NUMBER NOT NULL,
COMPARTMENT_NAME VARCHAR(5) NOT NULL,
CLASS VARCHAR(15),
CONSTRAINT COMPARTMENTS_FK FOREIGN KEY(TRAIN_ID) REFERENCES TRAINS(TRAIN_ID)
);

-- DROP TABLE SEATS;

CREATE TABLE SEATS (
    COMPARTMENT_ID NUMBER,
    SEAT_NO NUMBER,
    CONSTRAINT SEATS_PK PRIMARY KEY (COMPARTMENT_ID, SEAT_NO),
    CONSTRAINT SEATS_FK FOREIGN KEY (COMPARTMENT_ID) REFERENCES COMPARTMENTS (COMPARTMENT_ID)
);


--RECHECK 
CREATE TABLE RESERVATION (
    PNR VARCHAR2(20) CONSTRAINT RESERVATION_PK PRIMARY KEY,
    COMPARTMENT_ID NUMBER NOT NULL,
    SEAT_NO NUMBER NOT NULL,
    FROM_ST NUMBER NOT NULL,
    TO_ST NUMBER NOT NULL,
    DATE_OF_JOURNEY DATE NOT NULL,
    CONSTRAINT RESERVATION_FK1 FOREIGN KEY (COMPARTMENT_ID, SEAT_NO) REFERENCES SEATS (COMPARTMENT_ID, SEAT_NO),
    CONSTRAINT RESERVATION_FK2 FOREIGN KEY (FROM_ST) REFERENCES STATIONS (STATION_ID),
    CONSTRAINT RESERVATION_FK3 FOREIGN KEY (TO_ST) REFERENCES STATIONS (STATION_ID)
);



CREATE TABLE FARE (
    FROM_ST NUMBER,
    TO_ST NUMBER,
    AMOUNT NUMBER NOT NULL,
    CONSTRAINT FARE_PK PRIMARY KEY (FROM_ST, TO_ST),
    CONSTRAINT FARE_FK1 FOREIGN KEY (FROM_ST) REFERENCES STATIONS (STATION_ID),
    CONSTRAINT FARE_FK2 FOREIGN KEY (TO_ST) REFERENCES STATIONS (STATION_ID)
);

CREATE TABLE PAYMENT(
PAYMENT_ID VARCHAR(20) CONSTRAINT PAYMENT_PK PRIMARY KEY,
PNR VARCHAR(20) NOT NULL,
AMOUNT NUMBER NOT NULL,
PAYMENT_TYPE VARCHAR(20) NOT NULL,
CONSTRAINT PAYMENT_FK FOREIGN KEY(PNR) REFERENCES RESERVATION(PNR)
);


CREATE TABLE MAKES (
    NID VARCHAR2(15),
    PNR VARCHAR2(20),
    ISSUE_DATE DATE NOT NULL,
    CONSTRAINT MAKES_PK PRIMARY KEY (NID, PNR),
    CONSTRAINT MAKES_FK1 FOREIGN KEY (NID) REFERENCES PASSENGERS (NID),
    CONSTRAINT MAKES_FK2 FOREIGN KEY (PNR) REFERENCES RESERVATION (PNR)
);

CREATE TABLE CHECKS (
    NID VARCHAR2(15),
    TRAIN_ID NUMBER,
    CONSTRAINT CHECKS_PK PRIMARY KEY (NID, TRAIN_ID),
    CONSTRAINT CHECKS_FK1 FOREIGN KEY (NID) REFERENCES PASSENGERS (NID),
    CONSTRAINT CHECKS_FK2 FOREIGN KEY (TRAIN_ID) REFERENCES TRAINS (TRAIN_ID)
);

CREATE TABLE CARD_PAYMENT(
CARD_NO VARCHAR2(20) CONSTRAINT CARD_PAYMENT_PK PRIMARY KEY,
CARD_HOLDER_NAME VARCHAR2(50) NOT NULL
);

CREATE TABLE MOBILE_BANKING(
AC_NO VARCHAR2(20) CONSTRAINT MOBILE_BANKING_PK PRIMARY KEY,
HOLDER_NAME VARCHAR2(50) NOT NULL
);

CREATE TABLE NEXUS_PAY(
CARD_NO VARCHAR2(20) CONSTRAINT NEXUS_PAY_PK PRIMARY KEY,
HOLDER_NAME VARCHAR2(50) NOT NULL
);

CREATE TABLE CARD_PAY (
    CARD_NO VARCHAR2(20),
    PAYMENT_ID VARCHAR2(20),
    CONSTRAINT CARD_PAY_PK PRIMARY KEY (CARD_NO, PAYMENT_ID),
    CONSTRAINT CARD_PAY_FK1 FOREIGN KEY (CARD_NO) REFERENCES CARD_PAYMENT (CARD_NO),
    CONSTRAINT CARD_PAY_FK2 FOREIGN KEY (PAYMENT_ID) REFERENCES PAYMENT (PAYMENT_ID)
);


CREATE TABLE MOBILE_PAY (
    AC_NO VARCHAR2(20),
    PAYMENT_ID VARCHAR2(20),
    CONSTRAINT MOBILE_PAY_PK PRIMARY KEY (AC_NO, PAYMENT_ID),
    CONSTRAINT MOBILE_PAY_FK1 FOREIGN KEY (AC_NO) REFERENCES MOBILE_BANKING (AC_NO),
    CONSTRAINT MOBILE_PAY_FK2 FOREIGN KEY (PAYMENT_ID) REFERENCES PAYMENT (PAYMENT_ID)
);


CREATE TABLE NEXUS_METHOD (
    CARD_NO VARCHAR2(20),
    PAYMENT_ID VARCHAR2(20),
    CONSTRAINT NEXUS_METHOD_PK PRIMARY KEY (CARD_NO, PAYMENT_ID),
    CONSTRAINT NEXUS_METHOD_FK1 FOREIGN KEY (CARD_NO) REFERENCES NEXUS_PAY (CARD_NO),
    CONSTRAINT NEXUS_METHOD_FK2 FOREIGN KEY (PAYMENT_ID) REFERENCES PAYMENT (PAYMENT_ID)
);













