INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (765, 1, NULL, '06:45 am', 'source',1);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (765, 757, '07:07 am', '07:12 am', 'inter',2);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (765, 758, '07:35 am', '07:37 am', 'inter',3);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (765, 759, '08:59 am', '09:09 am', 'inter',4);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (765, 581, '10:39 am', '10:42 am', 'inter',5);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (765, 226, '11:18 am', '11:21 am', 'inter',6);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (765, 762, '11:41 am', '11:43 am', 'inter',7);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (765, 102, '12:30 pm', '12:35 pm', 'inter',8);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (765, 242, '12:55 pm', '12:57 pm', 'inter',9);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (765, 76, '01:11 pm', '01:14 pm', 'inter',10);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (765, 5, '01:42 pm', '01:45 pm', 'inter',11);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (765, 4, '01:56 pm', '01:58 pm', 'inter',12);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (765, 35, '02:15 pm', '02:25 pm', 'inter',13);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (765, 8, '02:42 pm', '02:46 pm', 'inter',14);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (765, 19, '03:05 pm', '03:08 pm', 'inter',15);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (765, 20, '03:24 pm', '03:27 pm', 'inter',16);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (765, 21, '04:00 pm', NULL, 'dest',17);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (766, 21, NULL, '08:00 pm', 'source',1);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (766, 20, '08:18 pm', '08:21 pm', 'inter',2);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (766, 19, '08:37 pm', '08:40 pm', 'inter',3);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (766, 8, '08:59 pm', '09:04 pm', 'inter',4);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (766, 35, '09:20 pm', '09:40 pm', 'inter',5);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (766, 4, '09:58 pm', '10:01 pm', 'inter',6);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (766, 5, '10:12 pm', '10:15 pm', 'inter',7);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (766, 76, '10:44 pm', '10:47 pm', 'inter',8);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (766, 242, '11:00 pm', '11:02 pm', 'inter',9);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (766, 102, '11:20 pm', '11:25 pm', 'inter',10);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (766, 762, '11:47 pm', '11:49 pm', 'inter',11);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (766, 226, '12:10 am', '12:13 am', 'inter',12);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (766, 581, '01:15 am', '01:17 am', 'inter',13);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (766, 759, '02:58 am', '03:00 am', 'inter',14);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (766, 758, '04:21 am', '04:24 am', 'inter',15);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (766, 1, '05:30 am', NULL, 'dest',16);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (795, 82, NULL, '01:00 pm', 'source',1);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (795, 227, '01:30 pm', '01:32 pm', 'inter',2);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (795, 51, '01:55 pm', '02:15 pm', 'inter',3);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (795, 788, '02:55 pm', '02:57 pm', 'inter',4);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (795, 54, '03:08 pm', '03:10 pm', 'inter',5);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (795, 765, '03:34 pm', '03:37 pm', 'inter',6);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (795, 515, '03:56 pm', '03:59 pm', 'inter',7);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (795, 764, '04:40 pm', '04:44 pm', 'inter',8);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (795, 787, '04:56 pm', '04:59 pm', 'inter',9);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (795, 37, '05:21 pm', NULL, 'inter',10);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (795, 36, '06:00 pm', '06:10 pm', 'inter',11);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (795, 184, '06:42 pm', '06:45 pm', 'inter',12);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (795, 354, '07:15 pm', '07:18 pm', 'inter',13);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (795, 1, '08:45 pm', NULL, 'dest',14);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (796, 1, NULL, '11:45 pm', 'source',1);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (796, 354, '12:52 am', '12:55 am', 'inter',2);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (796, 184, '01:35 am', '01:38 am', 'inter',3);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (796, 36, '02:10 am', '02:25 am', 'inter',4);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (796, 37, '02:58 am', NULL, 'dest',5);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (796, 787, '03:22 am', '03:25 am', 'inter',6);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (796, 764, '03:45 am', '03:50 am', 'inter',7);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (796, 515, '04:19 am', '04:22 am', 'inter',8);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (796, 765, '04:44 am', '04:47 am', 'inter',9);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (796, 54, '05:12 am', '05:14 am', 'inter',10);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (796, 788, '05:26 am', '05:28 am', 'inter',11);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (796, 51, '06:00 am', '06:20 am', 'inter',12);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (796, 227, '06:39 am', '06:41 am', 'inter',13);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (796, 82, '07:20 am', NULL, 'dest',14);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (741, 47, NULL, '11:30 pm', 'source',1);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (741, 258, '12:50 am', '12:52 am', 'inter',2);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (741, 296, '01:30 am', '01:32 am', 'inter',3);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (741, 209, '01:55 am', '01:57 am', 'inter',4);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (741, 809, '02:47 am', '02:50 am', 'inter',5);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (741, 264, '03:07 am', '03:10 am', 'inter',6);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (741, 810, '03:30 am', '03:33 am', 'inter',7);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (741, 1, '05:15 am', NULL, 'dest',8);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (742, 1, NULL, '11:15 pm', 'source',1);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (742, 757, '11:38 pm', '11:43 pm', 'inter',2);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (742, 810, '12:49 am', '12:52 am', 'inter',3);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (742, 264, '01:12 am', '01:16 am', 'inter',4);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (742, 809, '01:45 am', '01:50 am', 'inter',5);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (742, 209, '02:33 am', '02:35 am', 'inter',6);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (742, 296, '02:57 am', '03:00 am', 'inter',7);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (742, 258, '03:40 am', '03:42 am', 'inter',8);
INSERT INTO C##RAIL.TRAIN_STOPS (train_id, station_id, arr_time, dept_time, stop_type,stop_no) VALUES (742, 47, '05:15 am', NULL, 'dest',9);